name: ambiente_matematica_computacional
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=24.0
  - numpy=1.26.4
  - pandas=2.1.4
  - scikit-learn=1.3.2
  - matplotlib=3.8.2
  - scipy=1.11.4
  - seaborn=0.13.2
  - jupyterlab=4.2.5
  - pip:
      - pycaret[analysis]==3.3.2
      - ydata-profiling==4.8.3
      - lightgbm==4.3.0
      - xgboost==2.0.3
      - catboost==1.2.5
      - streamlit
      - streamlit-ydata-profiling
      - clickhouse-connect==0.8.18
      - python-dotenv==1.1.1
      - kaggle
      - shap
      - scikit-plot